export enum ApplicationEventName {
    FLOW_CREATED = 'flow.created',
    FLOW_DELETED = 'flow.deleted',
    FLOW_UPDATED = 'flow.updated',
    FLOW_RUN_RESUMED = 'flow.run.resumed',
    FLOW_RUN_STARTED = 'flow.run.started',
    FLOW_RUN_FINISHED = 'flow.run.finished',
    FOLDER_CREATED = 'folder.created',
    FOLDER_UPDATED = 'folder.updated',
    FOLDER_DELETED = 'folder.deleted',
    CONNECTION_UPSERTED = 'connection.upserted',
    CONNECTION_DELETED = 'connection.deleted',
    USER_SIGNED_UP = 'user.signed.up',
    USER_SIGNED_IN = 'user.signed.in',
    USER_PASSWORD_RESET = 'user.password.reset',
    USER_EMAIL_VERIFIED = 'user.email.verified',
    SIGNING_KEY_CREATED = 'signing.key.created',
    PROJECT_ROLE_CREATED = 'project.role.created',
    PROJECT_ROLE_DELETED = 'project.role.deleted',
    PROJECT_ROLE_UPDATED = 'project.role.updated',
    PROJECT_RELEASE_CREATED = 'project.release.created',
}
